export interface YoloLabel {
  classId: number;
  x: number; // Center X (0-1)
  y: number; // Center Y (0-1)
  w: number; // Width (0-1)
  h: number; // Height (0-1)
  isPredicted?: boolean; // Flag to indicate if label was generated by model
  confidence?: number; // Prediction confidence score (0-1)
}

export type ReviewData = Record<string, string[]>; // Filename -> Array of LabelHashes

// Define minimal interfaces for File System Access API
export interface FileSystemHandle {
  kind: 'file' | 'directory';
  name: string;
  queryPermission(descriptor?: { mode?: 'read' | 'readwrite' }): Promise<'granted' | 'denied' | 'prompt'>;
  requestPermission(descriptor?: { mode?: 'read' | 'readwrite' }): Promise<'granted' | 'denied' | 'prompt'>;
}

export interface FileSystemFileHandle extends FileSystemHandle {
  kind: 'file';
  getFile(): Promise<File>;
  createWritable(options?: any): Promise<FileSystemWritableFileStream>;
}

export interface FileSystemDirectoryHandle extends FileSystemHandle {
  kind: 'directory';
  values(): AsyncIterableIterator<FileSystemHandle | FileSystemFileHandle | FileSystemDirectoryHandle>;
  getFileHandle(name: string, options?: { create?: boolean }): Promise<FileSystemFileHandle>;
  getDirectoryHandle(name: string, options?: { create?: boolean }): Promise<FileSystemDirectoryHandle>;
}

export interface FileSystemWritableFileStream extends WritableStream {
  write(data: any): Promise<void>;
  seek(position: number): Promise<void>;
  truncate(size: number): Promise<void>;
  close(): Promise<void>;
}

export interface ImageAsset {
  name: string;
  url: string;
  file?: File;
  // Handle for potential future use
  handle?: FileSystemFileHandle; 
}

export interface DatasetContext {
  images: ImageAsset[];
  labels: Map<string, string>; // Filename (without ext) -> content
  classes: string[];
}